// Generated by Apple Swift version 4.1.2 (swiftlang-902.0.54 clang-902.0.39.2)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <objc/NSObject.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR __attribute__((enum_extensibility(open)))
# else
#  define SWIFT_ENUM_ATTR
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name) enum _name : _type _name; enum SWIFT_ENUM_ATTR SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME) SWIFT_ENUM(_type, _name)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if __has_feature(modules)
@import ObjectiveC;
@import Foundation;
@import UIKit;
@import CoreGraphics;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="TYYSDK",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

/// 初始化返回状态码
typedef SWIFT_ENUM(NSInteger, InitState) {
  InitStateSuccess = 0,
  InitStateFailed = 1,
  InitStateNeedUpdate = 2,
};

/// 登录返回状态码
typedef SWIFT_ENUM(NSInteger, LoginState) {
  LoginStateSuccess = 0,
  LoginStateFailed = 1,
  LoginStateCancel = 2,
};

/// 用户退出登录状态
typedef SWIFT_ENUM(NSInteger, LogoutState) {
/// 正常退出
  LogoutStateNormal = 0,
/// 登录失效
  LogoutStateLogin_Invalid = 1,
/// 切换账号
  LogoutStateSwitch_Account = 2,
};

typedef SWIFT_ENUM(NSInteger, NormalState) {
  NormalStateSuccess = 0,
  NormalStateFailed = 1,
};

/// 支付返回状态码
typedef SWIFT_ENUM(NSInteger, PayState) {
  PayStateSuccess = 0,
  PayStateFailed = 1,
  PayStateCancel = 2,
  PayStateUnknown = 3,
};


SWIFT_CLASS("_TtC6TYYSDK10TYPayParam")
@interface TYPayParam : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC6TYYSDK21TYYSupportApplication")
@interface TYYSupportApplication : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC6TYYSDK17TYROwnApplication")
@interface TYROwnApplication : TYYSupportApplication
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC6TYYSDK15TYYSupportExtra")
@interface TYYSupportExtra : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC6TYYSDK11TYROwnExtra")
@interface TYROwnExtra : TYYSupportExtra
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC6TYYSDK14TYYSupportInit")
@interface TYYSupportInit : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC6TYYSDK10TYROwnInit")
@interface TYROwnInit : TYYSupportInit
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC6TYYSDK15TYYSupportLogin")
@interface TYYSupportLogin : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC6TYYSDK11TYROwnLogin")
@interface TYROwnLogin : TYYSupportLogin
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC6TYYSDK13TYYSupportPay")
@interface TYYSupportPay : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC6TYYSDK9TYROwnPay")
@interface TYROwnPay : TYYSupportPay
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC6TYYSDK16TYYSupportSubmit")
@interface TYYSupportSubmit : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC6TYYSDK12TYROwnSubmit")
@interface TYROwnSubmit : TYYSupportSubmit
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC6TYYSDK11TYSdkParams")
@interface TYSdkParams : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC6TYYSDK7TYToast")
@interface TYToast : NSOperation
@property (nonatomic, getter=isExecuting) BOOL executing;
@property (nonatomic, getter=isFinished) BOOL finished;
- (void)cancel;
- (void)start;
- (void)main;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end

@class UIColor;
@class UIFont;
@class NSCoder;
@class UIEvent;

SWIFT_CLASS("_TtC6TYYSDK11TYToastView")
@interface TYToastView : UIView
/// The background view’s color.
@property (nonatomic, strong) UIColor * _Nullable backgroundColor;
/// The background view’s corner radius.
@property (nonatomic) CGFloat cornerRadius;
/// The inset of the text label.
@property (nonatomic) UIEdgeInsets textInsets;
/// The color of the text label’s text.
@property (nonatomic, strong) UIColor * _Nullable textColor;
/// The font of the text label.
@property (nonatomic, strong) UIFont * _Nullable font;
/// The bottom offset from the screen’s bottom in portrait mode.
@property (nonatomic) CGFloat bottomOffsetPortrait;
/// The bottom offset from the screen’s bottom in landscape mode.
@property (nonatomic) CGFloat bottomOffsetLandscape;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder;
- (void)layoutSubviews;
- (UIView * _Nullable)hitTest:(CGPoint)point withEvent:(UIEvent * _Null_unspecified)event SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
@end

@class UIViewController;

SWIFT_CLASS("_TtC6TYYSDK13TYToastWindow")
@interface TYToastWindow : UIWindow
@property (nonatomic, strong) UIViewController * _Nullable rootViewController;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC6TYYSDK17TYYCPUserInfoData")
@interface TYYCPUserInfoData : NSObject
@property (nonatomic, copy) NSString * _Nonnull id;
@property (nonatomic, copy) NSString * _Nonnull cpGameId;
@property (nonatomic, copy) NSString * _Nonnull agentId;
@property (nonatomic, copy) NSString * _Nonnull userId;
@property (nonatomic, copy) NSString * _Nonnull lastLoginIp;
@property (nonatomic, copy) NSString * _Nonnull cpUpdateTime;
@property (nonatomic, copy) NSString * _Nonnull lastLoginTime;
@property (nonatomic, copy) NSString * _Nonnull tatolMoney;
@property (nonatomic, copy) NSString * _Nonnull roleId;
@property (nonatomic, copy) NSString * _Nonnull roleName;
@property (nonatomic, copy) NSString * _Nonnull roleLevel;
@property (nonatomic, copy) NSString * _Nonnull zoneId;
@property (nonatomic, copy) NSString * _Nonnull zoneName;
@property (nonatomic, copy) NSString * _Nonnull balance;
@property (nonatomic, copy) NSString * _Nonnull vip;
@property (nonatomic, copy) NSString * _Nonnull partyname;
@property (nonatomic, copy) NSString * _Nonnull rolecTime;
@property (nonatomic, copy) NSString * _Nonnull roleLevelimTime;
@property (nonatomic, copy) NSString * _Nonnull attach;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC6TYYSDK19TYYChatUploadParams")
@interface TYYChatUploadParams : NSObject
/// 角色id
@property (nonatomic, copy) NSString * _Nonnull roleId;
/// 角色名称
@property (nonatomic, copy) NSString * _Nonnull roleName;
/// 聊天类型
@property (nonatomic, copy) NSString * _Nonnull typeName;
/// 聊天内容
@property (nonatomic, copy) NSString * _Nonnull content;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC6TYYSDK18TYYLoginResultData")
@interface TYYLoginResultData : NSObject
/// 登录后token
@property (nonatomic, copy) NSString * _Nonnull token;
/// 用户id
@property (nonatomic, copy) NSString * _Nonnull id;
/// 额外数据
@property (nonatomic, copy) NSString * _Nonnull rawJson;
/// 错误信息
@property (nonatomic, copy) NSString * _Nullable msg;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


/// 支付返回结构
SWIFT_CLASS("_TtC6TYYSDK10TYYPayData")
@interface TYYPayData : NSObject
/// 支付金额
@property (nonatomic, copy) NSString * _Nonnull amount;
/// 支付id,可能为空
@property (nonatomic, copy) NSString * _Nonnull payID;
/// 错误消息
@property (nonatomic, copy) NSString * _Nullable msg;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC6TYYSDK16TYYPayResultData")
@interface TYYPayResultData : NSObject
/// 发行订单编号
@property (nonatomic, copy) NSString * _Nonnull releaseOrderNo;
/// 代理订单信息 json字符串 每个公司可能都不一样,所以先用字符串保存
@property (nonatomic, copy) NSString * _Nonnull agentOrderInfo;
/// 支付跳转地址 自己支付时才会使用
@property (nonatomic, copy) NSString * _Nonnull payUrl;
/// 游戏用户角色信息
@property (nonatomic, strong) TYYCPUserInfoData * _Nullable cpUserInfo;
/// 角色id
@property (nonatomic, copy) NSString * _Nonnull roleId;
/// 支付金额
@property (nonatomic) double amount;
/// 购买商品名称
@property (nonatomic, copy) NSString * _Nonnull productName;
/// 错误信息
@property (nonatomic, copy) NSString * _Nullable msg;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC6TYYSDK18TYYPayUploadParams")
@interface TYYPayUploadParams : NSObject
/// 购买数量
@property (nonatomic, copy) NSString * _Nonnull buyNum;
/// 玩家当前拥有的游戏币数量
@property (nonatomic, copy) NSString * _Nonnull coinNum;
/// 购买商品ID
@property (nonatomic, copy) NSString * _Nonnull productId;
/// 购买商品的描述
@property (nonatomic, copy) NSString * _Nonnull productDes;
/// 角色等级
@property (nonatomic, copy) NSString * _Nonnull roleLevel;
/// 角色等级
@property (nonatomic, copy) NSString * _Nonnull rolename;
/// 服务器id
@property (nonatomic, copy) NSString * _Nonnull serverId;
/// 服务器名称
@property (nonatomic, copy) NSString * _Nonnull serverName;
/// 角色vip等级
@property (nonatomic, copy) NSString * _Nonnull vip;
/// <em><em><em><em><em><em><em><em><em><em><em><em><em><em><em><em>服务器暂时只需要以下数据</em></em></em></em></em></em></em></em></em></em></em></em></em></em></em></em>********
/// 角色id
@property (nonatomic, copy) NSString * _Nonnull roleId;
/// 游戏订单编号
@property (nonatomic, copy) NSString * _Nonnull cporderSN;
/// 支付总金额
@property (nonatomic) double amount;
/// 购买商品名称
@property (nonatomic, copy) NSString * _Nonnull productName;
/// 额外参数
@property (nonatomic, copy) NSString * _Nonnull attach;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class TYYUserInfoUploadParams;
@class UIApplication;

SWIFT_CLASS("_TtC6TYYSDK6TYYSDK")
@interface TYYSDK : NSObject
+ (TYYSDK * _Nonnull)share SWIFT_WARN_UNUSED_RESULT;
/// 是否输出Log
+ (void)setDebugWithDebug:(BOOL)debug;
/// 是否汇报崩溃日志
+ (void)setReportWithReport:(BOOL)report;
/// (必接)初始化SDK
- (void)initSdkWithInitCallback:(void (^ _Nonnull)(enum InitState, NSString * _Nullable))initCallback loginCallback:(void (^ _Nonnull)(enum LoginState, TYYLoginResultData * _Nullable))loginCallback payCallback:(void (^ _Nonnull)(enum PayState, TYYPayData * _Nonnull))payCallback logoutCallback:(void (^ _Nonnull)(enum LogoutState, NSString * _Nullable))logoutCallback SWIFT_METHOD_FAMILY(none);
/// (必接)登录
- (void)login;
/// (选接)注销或者登出
- (void)logout;
/// (必接)支付充值
- (void)pay:(TYYPayUploadParams * _Nonnull)payData;
/// (必接)上传角色信息
- (void)uploadUserInfo:(TYYUserInfoUploadParams * _Nonnull)infoData callback:(void (^ _Nullable)(enum NormalState, NSString * _Nullable))callback;
/// (选接)上传聊天信息
- (void)uploadChat:(TYYChatUploadParams * _Nonnull)chatData callback:(void (^ _Nullable)(enum NormalState, NSString * _Nullable))callback;
/// (选接)显示主界面
- (void)showMainView;
/// (必接)Application回调,支付使用
- (BOOL)application:(UIApplication * _Nonnull)application didFinishLaunchingWithOptions:(NSDictionary<UIApplicationLaunchOptionsKey, id> * _Nullable)launchOptions SWIFT_WARN_UNUSED_RESULT;
/// (必接)Application回调,支付使用
- (BOOL)application:(UIApplication * _Nonnull)application open:(NSURL * _Nonnull)url options:(NSDictionary<UIApplicationOpenURLOptionsKey, id> * _Nonnull)options SWIFT_WARN_UNUSED_RESULT SWIFT_AVAILABILITY(ios,introduced=9.0);
/// (必接)Application回调,支付使用
- (void)applicationWillEnterForeground:(UIApplication * _Nonnull)application;
/// (必接)Application回调,支付使用
- (BOOL)application:(UIApplication * _Nonnull)application open:(NSURL * _Nonnull)url sourceApplication:(NSString * _Nullable)sourceApplication annotation:(id _Nonnull)annotation SWIFT_WARN_UNUSED_RESULT;
/// (选接)Application回调,支付使用
- (BOOL)application:(UIApplication * _Nonnull)application handleOpen:(NSURL * _Nonnull)url SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end







enum TYYUserInfoUploadType : NSInteger;

SWIFT_CLASS("_TtC6TYYSDK23TYYUserInfoUploadParams")
@interface TYYUserInfoUploadParams : NSObject
/// 角色id
@property (nonatomic, copy) NSString * _Nonnull roleId;
/// 角色名称
@property (nonatomic, copy) NSString * _Nonnull roleName;
/// 角色等级
@property (nonatomic, copy) NSString * _Nonnull roleLevel;
/// 区服id
@property (nonatomic, copy) NSString * _Nonnull zoneId;
/// 区服名称
@property (nonatomic, copy) NSString * _Nonnull zoneName;
/// 帐户余额
@property (nonatomic, copy) NSString * _Nonnull balance;
/// vip等级
@property (nonatomic, copy) NSString * _Nonnull vip;
/// 帮派名称
@property (nonatomic, copy) NSString * _Nonnull partyName;
/// cp传下来的原始信息
@property (nonatomic, copy) NSString * _Nonnull attach;
@property (nonatomic) enum TYYUserInfoUploadType type;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
@end


SWIFT_CLASS("_TtC6TYYSDK27TYYUpdateUserInfoResultData")
@interface TYYUpdateUserInfoResultData : TYYUserInfoUploadParams
/// 当前角色拥有的游戏币数量
@property (nonatomic, copy) NSString * _Nonnull coinNum;
/// 角色创建时间   单位为秒
@property (nonatomic, copy) NSString * _Nonnull roleCreateTime;
/// 角色等级变化时间 单位为秒
@property (nonatomic, copy) NSString * _Nonnull roleLevelUpTime;
/// 职业
@property (nonatomic, copy) NSString * _Nonnull profession;
/// 是否成功
@property (nonatomic) BOOL isSuccess;
@property (nonatomic, copy) NSDictionary<NSString *, id> * _Nullable rawInfo;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


typedef SWIFT_ENUM(NSInteger, TYYUserInfoUploadType) {
  TYYUserInfoUploadTypeUNDEFINED = 0,
  TYYUserInfoUploadTypeJOIN_SERVER = 1,
  TYYUserInfoUploadTypeCREATE_ROLE = 2,
  TYYUserInfoUploadTypeUPGRADE = 3,
  TYYUserInfoUploadTypeFACTION = 4,
  TYYUserInfoUploadTypeEXIT = 5,
  TYYUserInfoUploadTypeOTHER = 6,
};

@class NSBundle;

/// 目前主要是做监听摇一摇的功能,请将主ViewController继承于该类,如有CP也调用,请在motionBegan中调用super方法
SWIFT_CLASS("_TtC6TYYSDK17TYYViewController")
@interface TYYViewController : UIViewController
/// 用于监听摇一摇
- (void)viewWillAppear:(BOOL)animated;
/// 用于监听摇一摇
- (void)viewWillDisappear:(BOOL)animated;
- (void)motionBegan:(UIEventSubtype)motion withEvent:(UIEvent * _Nullable)event;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC6TYYSDK9TestTYSDK")
@interface TestTYSDK : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end









#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop
